spring.application.name=antigolpe

# Configuração do Servidor
server.port=8080

# --- CONFIGURAÇÃO DO POSTGRESQL ---
# Substitui completamente a configuração do H2
spring.datasource.url=jdbc:postgresql://localhost:5432/antigolpe_db
spring.datasource.username=antigolpe_user
spring.datasource.password=antigolpe123

# Configurações do Hibernate para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# --- FIM DA CONFIGURAÇÃO DO POSTGRESQL ---

# Configuração da Chave Secreta do JWT
# IMPORTANTE: Em produção, use uma chave muito mais forte e armazene-a de forma segura (ex: variáveis de ambiente)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970