spring.application.name=antigolpe

# Configuração do Servidor
server.port=8080

# --- CONFIGURAÇÃO DO POSTGRESQL (Para o Render) ---
# Lê as variáveis de ambiente que vamos criar no dashboard do Render
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Configurações do Hibernate para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# --- FIM DA CONFIGURAÇÃO DO POSTGRESQL ---

# Configuração da Chave Secreta do JWT (Para o Render)
# Lê a variável de ambiente que vamos criar no dashboard do Render
application.security.jwt.secret-key=${JWT_SECRET}